/*
Do NOT edit this file!
This file will be deleted with the next Jenkins/Grunt build.
Build Date: Thursday, September 7th, 2017, 9:31:52 PM UTC
Version:b19f2470b86c168f9a2b11cf97a3e8f72d9b062f_1504819913
Questions? contact Paolo Vaca 
*/

define("index-desktop-startup",function(){}),require(["index-desktop-startup"]);