/*
Do NOT edit this file!
This file will be deleted with the next Jenkins/Grunt build.
Build Date: Friday, September 1st, 2017, 4:27:04 PM UTC
Version:5111a2eac26f542c7d34042a3b2bf3d4af9c2262_1504283224
Questions? contact Paolo Vaca 
*/

define("section-desktop-startup",["require","exports","module"],function(a,b,c){console.log("desktop section startup")}),require(["section-desktop-startup"]);